### ISSUE TITLE
Error: null is not an object (evaluating 'document.querySelector(".dialog").length')

### ISSUE THREAD

**Issue by gitarno** [leonardosalles/ngMobileDialog#1]
Updated to latest version and came these changes, there was trouble running the application.

Error: null is not an object (evaluating 'document.querySelector(".dialog").length')

**Comment by leonardosalles** [comment]
Did you check the querySelector support at you browser/device? May require a querySelector polyfill, try this aproach if the problem persist you can create a plunkr with the issue.

Try this [querySelector Polyfill](https://github.com/mtsyganov/queryselector-polyfill)

**Comment by leonardosalles** [comment]
Did you check the querySelector support at you browser/device? May require a querySelector polyfill, try this aproach if the problem persist you can create a plunkr with the issue?

Try this [querySelector Polyfill](https://github.com/mtsyganov/queryselector-polyfill)

**Comment by leonardosalles** [comment]
@gitarno Do you have added the polyfill? It works for you? Can you please confirm it so the issue will be closed, thanks.

**Comment by leonardosalles** [comment]
The user that was reported this issue dont provide any adittional data. Closing issue.
